# Generated by Django 3.2.12 on 2022-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(help_text='activity description', max_length=600),
        ),
    ]
