# Generated by Django 3.2.12 on 2022-03-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='end_date',
            field=models.DateField(blank=True, help_text='enter completed date', null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='start_date',
            field=models.DateField(blank=True, help_text='enter start date', null=True),
        ),
    ]
