# Generated by Django 3.2.12 on 2022-02-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_activities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.volunteer'),
        ),
    ]
