# Generated by Django 3.2.12 on 2022-03-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220301_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialing',
            name='peer_reviewer_1',
            field=models.CharField(blank=True, help_text='enter peer_reviewer_1', max_length=100),
        ),
        migrations.AddField(
            model_name='credentialing',
            name='peer_reviewer_2',
            field=models.CharField(blank=True, help_text='enter peer_reviewer_2', max_length=100),
        ),
        migrations.AddField(
            model_name='credentialing',
            name='peer_reviewer_3',
            field=models.CharField(blank=True, help_text='enter peer_reviewer_3', max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.volunteer'),
        ),
        migrations.AlterField(
            model_name='credentialing',
            name='license_duedate',
            field=models.DateField(blank=True, help_text='enter start date', null=True),
        ),
    ]
