# Generated by Django 3.2.12 on 2022-03-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220302_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
