# Generated by Django 3.2.12 on 2022-03-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220302_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
