# Generated by Django 3.2.12 on 2022-03-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220302_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialing',
            name='type',
            field=models.CharField(choices=[('Intial', 'Intial'), ('Reappointment', 'Reappointment')], max_length=20),
        ),
    ]
